---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    shell: /root/apache-tomcat-8.5.59/bin/shutdown.sh
  - name: Check that war file exist
    stat:
      path: /root/apache-tomcat-8.5.59/webapps/gameoflife.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /root/apache-tomcat-8.5.59/webapps/gameoflife.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /root/apache-tomcat-8.5.59/webapps/gameoflife
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /root/apache-tomcat-8.5.59/webapps/gameoflife
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
       url: http://3.6.39.93:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=mygameoflife&p=war&v=LATEST
       dest: /root/apache-tomcat-8.5.59/webapps/gameoflife.war
  - name: Start Tomcat
    shell: /root/apache-tomcat-8.5.59/bin/startup.sh
